// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:56961e40-e4d3-4f73-9890-bc8c3cf934c4",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_OHGgAB6Lc",
    "aws_user_pools_web_client_id": "3el00rbpc15nsuv37k8jmg93en",
    "oauth": {}
};


export default awsmobile;
